steps:
  - name: ':allthethings: Running test script'
    command:
     - "./scripts/test.sh"

  - name: ':aws: run aws command'
    command:
     - "./script/aws.sh"

  - block: ':thinking_face: Do you want to continue'

  - name: ':docker: pulling image'
    plugins:
      docker-compose:
        pull: myimage
        run: myimage