steps:
  - label: 'test docker pull'
      command: "docker pull library/hello-world"

  # - name: ':heavy_check_mark: Validate'
  #   plugins:
  #     docker-compose:
  #       pull: myimage
  #       run: myimage
